### ISSUE TITLE
Data set not found on ESO servers???

### ISSUE THREAD

**Issue by sousasag** [jdavidrcamacho/StarSearch#10]
I am getting the error bellow, but the data set could be retrieved through the download script that comes with the eso request email.

Any idea what could be the problem?

```
In [21]: query.GetInstrumentData('AD Leo', instrument = 'HARPS', downloadPath='/home/sousasag/Program
    ...: as/GIT_projects/Others/StarSearch/tmpdir/download')                                         

*** Searching for HARPS results ***

this /home/sousasag/Programas/GIT_projects/Others/StarSearch/tmpdir/download
INFO: Detecting already downloaded datasets... [starsearch.core]
INFO: Checking availability of datasets to download... [starsearch.core]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-21-0c20b5fc6ca8> in <module>
----> 1 query.GetInstrumentData('AD Leo', instrument = 'HARPS', downloadPath='/home/sousasag/Programas/GIT_projects/Others/StarSearch/tmpdir/download')

~/Programas/GIT_projects/Others/StarSearch/starsearch/phase3Archive.py in GetInstrumentData(self, star, instrument, downloadPath, date, SNR)
    357         print('\n*** Searching for {0} results ***\n'.format(instrument))
    358         if instrument.upper() in checkInstruments:
--> 359             self._searchAndDownload(star, instrument, downloadPath, date, SNR)
    360         else:
    361             print('No {0} data for {1}\n'.format(instrument, star))

~/Programas/GIT_projects/Others/StarSearch/starsearch/phase3Archive.py in _searchAndDownload(self, star, instrument, downloadPath, date, SNR)
    262             print('this', downloadPath)
    263             self.eso.retrieve_data(datasets = starARCFILE, 
--> 264                                    destination = downloadPath)
    265         else:
    266             self.eso.retrieve_data(datasets = starARCFILE)

~/Programas/GIT_projects/Others/StarSearch/starsearch/core.py in retrieve_data(self, datasets, continuation, destination, with_calib, request_all_objects)
    702                                                     valid_datasets) if not v]
    703             raise ValueError("The following data sets were not found on the "
--> 704                              "ESO servers: {0}".format(invalid_datasets))
    705         # Third: Download the other datasets
    706         log.info("Downloading datasets...")

ValueError: The following data sets were not found on the ESO servers: ['ADP.2014-09-16T11:03:32.720']

```

**Comment by jdavidrcamacho** [comment]
Sorry for the late reply, in my first try I got something similar 

```
user.GetInstrumentData('AD Leo', instrument='HARPS', downloadPath='/home/camacho/ADLeo')

*** Searching for HARPS results ***

INFO: Detecting already downloaded datasets... [starsearch.core]
INFO: Checking availability of datasets to download... [starsearch.core]
Traceback (most recent call last):

  File "<ipython-input-2-5aff0814b15a>", line 1, in <module>
    user.GetInstrumentData('AD Leo', instrument='HARPS', downloadPath='/home/camacho/ADLeo')

  File "/home/camacho/Github/StarSearch/starsearch/phase3Archive.py", line 359, in GetInstrumentData
    self._searchAndDownload(star, instrument, downloadPath, date, SNR)

  File "/home/camacho/Github/StarSearch/starsearch/phase3Archive.py", line 264, in _searchAndDownload
    destination = downloadPath)

  File "/home/camacho/Github/StarSearch/starsearch/core.py", line 704, in retrieve_data
    "ESO servers: {0}".format(invalid_datasets))

ValueError: The following data sets were not found on the ESO servers: ['ADP.2014-09-16T11:03:32.720']
```

After cleaning the cache of .astropy/cache/astroquery/ESO it worked

```
user.GetInstrumentData('AD Leo', instrument='HARPS', downloadPath='/home/camacho/ADLeo')

*** Searching for HARPS results ***

INFO: Detecting already downloaded datasets... [starsearch.core]
INFO: Checking availability of datasets to download... [starsearch.core]
INFO: Downloading datasets... [starsearch.core]
INFO: Contacting retrieval server... [starsearch.core]
INFO: Staging request... [starsearch.core]
INFO: Staging form is at https://dataportal.eso.org/rh/requests/jdcamacho/567678 [starsearch.core]
                   3s elapsedINFO: Downloading 58 files... [starsearch.core]
INFO: Downloading file 1/58: ADP.2014-09-16T11:03:32.720.fits... [starsearch.core]
Downloading URL http://dataportal.eso.org/dataPortal/requests/jdcamacho/567678/SAF/ADP.2014-09-16T11:03:32.720/ADP.2014-09-16T11:03:32.720.fits to /home/camacho/.astropy/cache/astroquery/Eso/ADP.2014-09-16T11:03:32.720.fits ... [Done]
INFO: Copying file ADP.2014-09-16T11:03:32.720.fits to /home/camacho/ADLeo... [starsearch.core]
INFO: Downloading file 2/58: ADP.2014-09-16T11:03:58.113.fits... [starsearch.core]
Downloading URL http://dataportal.eso.org/dataPortal/requests/jdcamacho/567678/SAF/ADP.2014-09-16T11:03:58.113/ADP.2014-09-16T11:03:58.113.fits to /home/camacho/.astropy/cache/astroquery/Eso/ADP.2014-09-16T11:03:58.113.fits ... [Done]
INFO: Copying file ADP.2014-09-16T11:03:58.113.fits to /home/camacho/ADLeo... [starsearch.core]
INFO: Downloading file 3/58: ADP.2014-09-16T11:04:06.613.fits... [starsearch.core]
Downloading URL http://dataportal.eso.org/dataPortal/requests/jdcamacho/567678/SAF/ADP.2014-09-16T11:04:06.613/ADP.2014-09-16T11:04:06.613.fits to /home/camacho/.astropy/cache/astroquery/Eso/ADP.2014-09-16T11:04:06.613.fits ... [Done]
INFO: Copying file ADP.2014-09-16T11:04:06.613.fits to /home/camacho/ADLeo... [starsearch.core]
INFO: Downloading file 4/58: ADP.2014-09-16T11:04:09.083.fits... [starsearch.core]
Downloading URL http://dataportal.eso.org/dataPortal/requests/jdcamacho/567678/SAF/ADP.2014-09-16T11:04:09.083/ADP.2014-09-16T11:04:09.083.fits to /home/camacho/.astropy/cache/astroquery/Eso/ADP.2014-09-16T11:04:09.083.fits ... [Done]
INFO: Copying file ADP.2014-09-16T11:04:09.083.fits to /home/camacho/ADLeo... [starsearch.core]
INFO: Downloading file 5/58: ADP.2014-09-16T11:04:27.553.fits... [starsearch.core]
Downloading URL http://dataportal.eso.org/dataPortal/requests/jdcamacho/567678/SAF/ADP.2014-09-16T11:04:27.553/ADP.2014-09-16T11:04:27.553.fits to /home/camacho/.astropy/cache/astroquery/Eso/ADP.2014-09-16T11:04:27.553.fits ... [Done]
INFO: Copying file ADP.2014-09-16T11:04:27.553.fits to /home/camacho/ADLeo... [starsearch.core]
INFO: Downloading file 6/58: ADP.2014-09-16T11:04:32.123.fits... [starsearch.core]
Downloading URL http://dataportal.eso.org/dataPortal/requests/jdcamacho/567678/SAF/ADP.2014-09-16T11:04:32.123/ADP.2014-09-16T11:04:32.123.fits to /home/camacho/.astropy/cache/astroquery/Eso/ADP.2014-09-16T11:04:32.123.fits ... [Done]
INFO: Copying file ADP.2014-09-16T11:04:32.123.fits to /home/camacho/ADLeo... [starsearch.core]
INFO: Downloading file 7/58: ADP.2014-09-16T11:04:38.040.fits... [starsearch.core]
```

I'll call this a bug and try to fix it as soon as possible

**Comment by jdavidrcamacho** [comment]
I think the starsearch version I have in my computer in IA has the cleaning cache issue fixed but I never push it to Github, I'll check it when I'm back to work
